# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
env:
  DB_DATABASE: test
  DB_USER: root
  DB_PASSWORD: root
  
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up JDK 11
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Set up MySQL    
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE ${{ env.DB_DATABASE }};grant all on test.* to test@'127.0.0.1' IDENTIFIED BY  'test123';" -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
